# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('avatar_url', models.URLField()),
            ],
        ),
    ]
